/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabibliotecagrupo3.vistas;

import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import sistemabibliotecagrupo3.modelos.Conexion;
import sistemabibliotecagrupo3.modelos.Ejemplar;
import sistemabibliotecagrupo3.modelos.EjemplarData;
import sistemabibliotecagrupo3.modelos.Lector;
import sistemabibliotecagrupo3.modelos.LectorData;
import sistemabibliotecagrupo3.modelos.Prestamo;
import sistemabibliotecagrupo3.modelos.PrestamoData;

/**
 *
 * @author Emiliano
 */
public class VistaSolicitarPrestamo extends javax.swing.JInternalFrame {
PrestamoData prestamoData;
    Conexion conexion=null;
    /**
     * Creates new form VistaSolicitarPrestamo
     */
    public VistaSolicitarPrestamo() {
              initComponents();
        
        
         try {
        conexion = new Conexion();
        Connection con = conexion.getConexion();
        prestamoData = new PrestamoData(conexion);
        prestamoData.revisionDePrestamosSinDevolucion();
//        prestamoData.revisionDePrestamosSinDevolucion();
    } catch (ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(this, "Error con los drivers de conexion");
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Problema de conexion con la base de datos");
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCEjemplar = new javax.swing.JComboBox<>();
        jCLector = new javax.swing.JComboBox<>();
        jBSolicitar = new javax.swing.JButton();
        jBDevolver = new javax.swing.JButton();
        jRSolicitar = new javax.swing.JRadioButton();
        jRDevolver = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("SOLICITUD O DEVOLUCION DE PRESTAMO");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("EJEMPLAR:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("LECTOR:");

        jBSolicitar.setText("SOLICITAR");
        jBSolicitar.setEnabled(false);
        jBSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSolicitarActionPerformed(evt);
            }
        });

        jBDevolver.setText("DEVOLVER");
        jBDevolver.setEnabled(false);
        jBDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDevolverActionPerformed(evt);
            }
        });

        jRSolicitar.setText("SOLICITAR");
        jRSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRSolicitarActionPerformed(evt);
            }
        });

        jRDevolver.setText("DEVOLVER");
        jRDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jBSolicitar)
                        .addGap(89, 89, 89)
                        .addComponent(jBDevolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCLector, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jRSolicitar)
                        .addGap(18, 18, 18)
                        .addComponent(jRDevolver)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRSolicitar)
                    .addComponent(jRDevolver))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSolicitar)
                    .addComponent(jBDevolver))
                .addGap(110, 110, 110))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarEjemplarS(String estado){
        EjemplarData auxE = new EjemplarData(conexion);
        ArrayList<Ejemplar>ejemplares=(ArrayList)auxE.obtenerEjemplaresSegunEstado(estado);
        
        for(Ejemplar a:ejemplares){
            jCEjemplar.addItem(a);
        } 
        jCEjemplar.setSelectedItem(null);
        }
    public void cargarLectoresP(){
        ArrayList<Lector> lectores = prestamoData.obtenerLectoresConPrestamosVigentes();
        for(Lector l:lectores){
            jCLector.addItem(l);
        } 
        jCLector.setSelectedItem(null);
    }
    
    public void cargarLectoresS(){
        LectorData auxL = new LectorData(conexion);
        ArrayList<Lector> lectores = (ArrayList)auxL.obtenerLectores();
        for(Lector l:lectores){
            jCLector.addItem(l);
        } 
        jCLector.setSelectedItem(null);
    }
    
    
    private void jBSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSolicitarActionPerformed
        // TODO add your handling code here:
//        prestamoData.revisionDePrestamosSinDevolucion();
        Lector auxL = (Lector)jCLector.getSelectedItem();
        prestamoData.revisarAltaLector(auxL);
        Ejemplar auxE = (Ejemplar)jCEjemplar.getSelectedItem();
        if(auxL!=null&&auxE!=null){
        prestamoData.solicitarPrestamo(auxE, auxL);
        Prestamo auxP = prestamoData.buscarPrestamo(auxL,auxE,true);
        
        }else{JOptionPane.showMessageDialog(null, "Tiene que seleccionar un lector y un ejemplar");}
        jCLector.removeAllItems();
        jCEjemplar.removeAllItems();
        cargarEjemplarS("Disponible");
        cargarLectoresS();
    }//GEN-LAST:event_jBSolicitarActionPerformed

    private void jBDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDevolverActionPerformed
        // TODO add your handling code here:
           Lector auxL = (Lector)jCLector.getSelectedItem();
        Ejemplar auxE =(Ejemplar)jCEjemplar.getSelectedItem();
        if(auxL!=null&&auxE!=null){
            Prestamo auxP = prestamoData.buscarPrestamo(auxL, auxE,true);
            if(auxP!=null&&auxP.getFechaDevolucion()==null){
            prestamoData.devolverPrestamo(auxP);
            }
            else if(auxP==null){
                JOptionPane.showMessageDialog(null, "El prestamo que desea devolver no esta en la base de datos");
            }else if(auxP.getFechaDevolucion()!=null){JOptionPane.showMessageDialog(null, "El prestamo ya fue devuelto anteriormente");}
        }else{JOptionPane.showMessageDialog(null, "Tiene que seleccionar un lector y un ejemplar");}
      
         jCLector.removeAllItems();
        jCEjemplar.removeAllItems();
         cargarEjemplarS("Prestado");
        cargarLectoresP();
    }//GEN-LAST:event_jBDevolverActionPerformed

    private void jRSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRSolicitarActionPerformed
        // TODO add your handling code here:
        jBSolicitar.setEnabled(true);
        jBDevolver.setEnabled(false);
        jRDevolver.setSelected(false);
        jCLector.removeAllItems();
        jCEjemplar.removeAllItems();
        cargarEjemplarS("Disponible");
        cargarLectoresS();
    }//GEN-LAST:event_jRSolicitarActionPerformed

    private void jRDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRDevolverActionPerformed
        // TODO add your handling code here:
        jBSolicitar.setEnabled(false);
        jBDevolver.setEnabled(true);
        jRSolicitar.setSelected(false);
        jCLector.removeAllItems();
        jCEjemplar.removeAllItems();
        cargarEjemplarS("Prestado");
        cargarLectoresP();
        
        
    }//GEN-LAST:event_jRDevolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDevolver;
    private javax.swing.JButton jBSolicitar;
    private javax.swing.JComboBox<Ejemplar> jCEjemplar;
    private javax.swing.JComboBox<Lector> jCLector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRDevolver;
    private javax.swing.JRadioButton jRSolicitar;
    // End of variables declaration//GEN-END:variables
}
