/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabibliotecagrupo3.vistas;
import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.xml.bind.DatatypeConverter;
import sistemabibliotecagrupo3.modelos.*;

/**
 *
 * @author Emiliano
 */
public class VistaPrestamos extends javax.swing.JInternalFrame {
    PrestamoData prestamoData;
    Conexion conexion=null;
    /**
     * Creates new form VistaPrestamos
     */
    public VistaPrestamos() {
          initComponents();
        
        
         try {
        conexion = new Conexion();
        Connection con = conexion.getConexion();
        prestamoData = new PrestamoData(conexion);
        cargarEjemplar();
        cargarLectores();
        jTPrestamo.setEditable(false);
        jTDevolucion.setEditable(false);
        jTMulta.setEditable(false);
        jBBuscar.setEnabled(false);
    } catch (ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(this, "Error con los drivers de conexion");
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Problema de conexion con la base de datos");
    }
         
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTId = new javax.swing.JTextField();
        jTPrestamo = new javax.swing.JTextField();
        jCEjemplar = new javax.swing.JComboBox<>();
        jCLector = new javax.swing.JComboBox<>();
        jTMulta = new javax.swing.JTextField();
        jTDevolucion = new javax.swing.JTextField();
        jBSolicitar = new javax.swing.JButton();
        jBDevolver = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBAlta = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("PRESTAMO");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setText("Ejemplar:");

        jLabel4.setText("Lector:");

        jLabel5.setText("Multa:");

        jLabel6.setText("Fecha prestamo:");

        jLabel7.setText("Fecha Devolucion");

        jTId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIdActionPerformed(evt);
            }
        });
        jTId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTIdKeyTyped(evt);
            }
        });

        jTPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPrestamoActionPerformed(evt);
            }
        });

        jCEjemplar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCEjemplarItemStateChanged(evt);
            }
        });
        jCEjemplar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCEjemplarKeyReleased(evt);
            }
        });

        jCLector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCLectorKeyReleased(evt);
            }
        });

        jBSolicitar.setText("Solicitar");
        jBSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSolicitarActionPerformed(evt);
            }
        });

        jBDevolver.setText("Devolver");
        jBDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDevolverActionPerformed(evt);
            }
        });

        jBBorrar.setText("Borrar");
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBAlta.setText("Dar alta");
        jBAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCLector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel1))
                                            .addComponent(jTId, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBBuscar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTDevolucion, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTPrestamo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTMulta))
                                        .addGap(20, 20, 20)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(145, 145, 145))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBSolicitar)
                        .addGap(18, 18, 18)
                        .addComponent(jBDevolver)
                        .addGap(18, 18, 18)
                        .addComponent(jBBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBAlta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBLimpiar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel2))
                                    .addComponent(jTId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jCLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jTMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jTDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSolicitar)
                    .addComponent(jBDevolver)
                    .addComponent(jBBorrar)
                    .addComponent(jBLimpiar)
                    .addComponent(jBAlta))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        int auxI = Integer.parseInt(jTId.getText());
        Prestamo auxP = prestamoData.buscarPrestamo(auxI);
        if(auxP!=null){
            jCEjemplar.removeAllItems();
            jCLector.removeAllItems();
            jCEjemplar.addItem(auxP.getEjemplar());
            jCLector.addItem(auxP.getLector());
            Multa m = auxP.getMulta();
            if(m!=null){
            jTMulta.setText(String.valueOf(m.getId_Multa()));
            }else{jTMulta.setText("No registra multa");}
            if(auxP.getFechaPrestamo()!=null){
            jTPrestamo.setText(auxP.getFechaPrestamo().toString());}
            else{jTPrestamo.setText("No registra fecha de prestamo");}
            if(auxP.getFechaDevolucion()!=null){
            jTDevolucion.setText(auxP.getFechaDevolucion().toString());}
            else{jTDevolucion.setText("No registra fecha de devolucion");}
        }else{JOptionPane.showMessageDialog(null, "el prestamo no esta en la base de datos");}
        
       
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jTIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIdActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jTIdActionPerformed

    private void jTIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTIdKeyTyped
        // TODO add your handling code here:
        
        char validar = evt.getKeyChar();
        if(!Character.isDigit(validar)){
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_jTIdKeyTyped

    private void jTIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTIdKeyReleased
        // TODO add your handling code here:
        habilitarBotonBuscar();
    }//GEN-LAST:event_jTIdKeyReleased

    private void jBSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSolicitarActionPerformed
        // TODO add your handling code here:
        Lector auxL = (Lector)jCLector.getSelectedItem();
        Ejemplar auxE = (Ejemplar)jCEjemplar.getSelectedItem();
        if(auxL!=null&&auxE!=null){
        prestamoData.solicitarPrestamo(auxE, auxL);
        Prestamo auxP = prestamoData.buscarPrestamo(auxL,auxE,true);
        jTPrestamo.setText(LocalDate.now().toString());
        }else{JOptionPane.showMessageDialog(null, "Tiene que seleccionar un lector y un ejemplar");}  
    }//GEN-LAST:event_jBSolicitarActionPerformed

    private void jCEjemplarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCEjemplarKeyReleased
        // TODO add your handling code here:
//        habilitarBotonSolicitar();
    }//GEN-LAST:event_jCEjemplarKeyReleased

    private void jCLectorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCLectorKeyReleased
        // TODO add your handling code here:
//        habilitarBotonSolicitar();
    }//GEN-LAST:event_jCLectorKeyReleased

    private void jBDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDevolverActionPerformed
        // TODO add your handling code here:
        Lector auxL = (Lector)jCLector.getSelectedItem();
        Ejemplar auxE =(Ejemplar)jCEjemplar.getSelectedItem();
        if(auxL!=null&&auxE!=null){
            Prestamo auxP = prestamoData.buscarPrestamo(auxL, auxE,true);
            if(auxP!=null){
            prestamoData.devolverPrestamo(auxP);
            jTPrestamo.setText(auxP.getFechaPrestamo().toString());
            jTDevolucion.setText(LocalDate.now().toString());
            }else if(auxP==null){
                JOptionPane.showMessageDialog(null, "El prestamo que desea eliminar no esta en la base de datos");
            }
        }else{JOptionPane.showMessageDialog(null, "Tiene que seleccionar un lector y un ejemplar");}
        
    }//GEN-LAST:event_jBDevolverActionPerformed

    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed
        // TODO add your handling code here:
        Lector auxL = (Lector)jCLector.getSelectedItem();
        Ejemplar auxE =(Ejemplar)jCEjemplar.getSelectedItem();
        if(auxL!=null&&auxE!=null){
        Prestamo auxP = prestamoData.buscarPrestamo(auxL, auxE,true);
        if(auxP!=null){
            prestamoData.darBajaPrestamo(auxP.getId_Prestamo());
            if(auxP.getFechaPrestamo()!=null){
            jTPrestamo.setText(auxP.getFechaPrestamo().toString());
            }else{
            jTPrestamo.setText("No registra fecha de solicitud");
            }
            if(auxP.getFechaDevolucion()!=null){
            jTDevolucion.setText(auxP.getFechaDevolucion().toString());
            }else{
            jTDevolucion.setText("No registra fecha de devolucion");       
            }
        }else{JOptionPane.showMessageDialog(null, "El prestamo ya se encuentra dado de baja");}
        }else{JOptionPane.showMessageDialog(null, "El prestamo que desea dar de baja no esta en la base de datos");}
    }//GEN-LAST:event_jBBorrarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        // TODO add your handling code here:
        jTId.setText("");
        jTMulta.setText("");
        jTPrestamo.setText("");
        jTDevolucion.setText("");
        jCLector.removeAllItems();
        jCEjemplar.removeAllItems();
        cargarEjemplar();
        cargarLectores();
        jCLector.setSelectedItem(null);
        jCEjemplar.setSelectedItem(null);

    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jTPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPrestamoActionPerformed

    private void jBAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAltaActionPerformed
        // TODO add your handling code here:
       Lector auxL = (Lector)jCLector.getSelectedItem();
        Ejemplar auxE =(Ejemplar)jCEjemplar.getSelectedItem();
        if(auxL!=null&&auxE!=null){
        Prestamo auxP = prestamoData.buscarPrestamo(auxL, auxE,false);
        if(auxP!=null){
            prestamoData.darBajaPrestamo(auxP.getId_Prestamo());
            if(auxP.getFechaPrestamo()!=null){
            jTPrestamo.setText(auxP.getFechaPrestamo().toString());
            }else{
            jTPrestamo.setText("No registra fecha de solicitud");
            }
            if(auxP.getFechaDevolucion()!=null){
            jTDevolucion.setText(auxP.getFechaDevolucion().toString());
            }else{
            jTDevolucion.setText("No registra fecha de devolucion");       
            }
        }else{JOptionPane.showMessageDialog(null, "El prestamo ya esta dado de alta");}
        }else{JOptionPane.showMessageDialog(null, "El prestamo que desea dar de alta no esta en la base de datos");}
    }//GEN-LAST:event_jBAltaActionPerformed

    private void jCEjemplarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCEjemplarItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCEjemplarItemStateChanged

    public void cargarEjemplar(){
        EjemplarData auxE = new EjemplarData(conexion);
        ArrayList<Ejemplar>ejemplares=(ArrayList)auxE.obtenerEjemplaresSegunEstado(true);
        for(Ejemplar a : ejemplares){
            jCEjemplar.addItem(a);
        } 
        jCEjemplar.setSelectedItem(null);
        }
    
    
    public void cargarLectores(){
        LectorData auxL = new LectorData(conexion);
        ArrayList<Lector> lectores = (ArrayList)auxL.obtenerLectoresSegunEstado(true);
        for(Lector l:lectores){
            jCLector.addItem(l);
        } 
        jCLector.setSelectedItem(null);
    }
    
    private void habilitarBotonBuscar(){
                 if(!jTId.getText().isEmpty()){
                     int auxI = Integer.parseInt(jTId.getText());
                     Prestamo auxP = prestamoData.buscarPrestamo(auxI);
                     if(auxP!=null){
                     jBBuscar.setEnabled(true);}
                     else{jBBuscar.setEnabled(false);}
                 }else{jBBuscar.setEnabled(false);}   
    }
    
//    private void habilitarBotonSolicitar(){
//        
//        if(jCEjemplar.getSelectedItem().toString()!=null&&jCLector.getSelectedItem().toString()!=null){
//        jBSolicitar.setEnabled(true);
//        }else{jBSolicitar.setEnabled(false);}
//    }

    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlta;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBDevolver;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBSolicitar;
    private javax.swing.JComboBox<Ejemplar> jCEjemplar;
    private javax.swing.JComboBox<Lector> jCLector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTDevolucion;
    private javax.swing.JTextField jTId;
    private javax.swing.JTextField jTMulta;
    private javax.swing.JTextField jTPrestamo;
    // End of variables declaration//GEN-END:variables
}
